import { Platform, Token } from "../coingecko";

export const tokens: Record<string, Token> = {
  terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6: {
    id: "mirror-protocol",
    symbol: "mir",
    name: "Mirror Protocol",
    platform: Platform.TERRA,
    logo:
      "https://assets.coingecko.com/coins/images/13295/large/mirror_logo_transparent.png?1611554658",
    decimals: 6,
    address: "terra15gwkyepfc6xgca5t5zefzwy42uts8l2m4g40k6",
  },
  terra1vxtwu4ehgzz77mnfwrntyrmgl64qjs75mpwqaz: {
    id: "mirrored-apple",
    symbol: "maapl",
    name: "Mirrored Apple",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/AAPL.png",
    decimals: 6,
    address: "terra1vxtwu4ehgzz77mnfwrntyrmgl64qjs75mpwqaz",
  },
  terra1h8arz2k547uvmpxctuwush3jzc8fun4s96qgwt: {
    id: "mirrored-google",
    symbol: "mgoogl",
    name: "Mirrored Google",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/GOOGL.png",
    decimals: 6,
    address: "terra1h8arz2k547uvmpxctuwush3jzc8fun4s96qgwt",
  },
  terra14y5affaarufk3uscy2vr6pe6w6zqf2wpjzn5sh: {
    id: "mirrored-tesla",
    symbol: "mtsla",
    name: "Mirrored Tesla",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/TSLA.png",
    decimals: 6,
    address: "terra14y5affaarufk3uscy2vr6pe6w6zqf2wpjzn5sh",
  },
  terra1jsxngqasf2zynj5kyh0tgq9mj3zksa5gk35j4k: {
    id: "mirrored-netflix",
    symbol: "mnflx",
    name: "Mirrored Netflix",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/NFLX.png",
    decimals: 6,
    address: "terra1jsxngqasf2zynj5kyh0tgq9mj3zksa5gk35j4k",
  },
  terra1csk6tc7pdmpr782w527hwhez6gfv632tyf72cp: {
    id: "mirrored-invesco-qqq-trust",
    symbol: "mqqq",
    name: "Mirrored Invesco QQQ Trust",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/QQQ.png",
    decimals: 6,
    address: "terra1csk6tc7pdmpr782w527hwhez6gfv632tyf72cp",
  },
  terra1cc3enj9qgchlrj34cnzhwuclc4vl2z3jl7tkqg: {
    id: "mirrored-twitter",
    symbol: "mtwtr",
    name: "Mirrored Twitter",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/TWTR.png",
    decimals: 6,
    address: "terra1cc3enj9qgchlrj34cnzhwuclc4vl2z3jl7tkqg",
  },
  terra1227ppwxxj3jxz8cfgq00jgnxqcny7ryenvkwj6: {
    id: "mirrored-microsoft",
    symbol: "mmsft",
    name: "Mirrored Microsoft",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/MSFT.png",
    decimals: 6,
    address: "terra1227ppwxxj3jxz8cfgq00jgnxqcny7ryenvkwj6",
  },
  terra165nd2qmrtszehcfrntlplzern7zl4ahtlhd5t2: {
    id: "mirrored-amazon",
    symbol: "mamzn",
    name: "Mirrored Amazon",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/AMZN.png",
    decimals: 6,
    address: "terra165nd2qmrtszehcfrntlplzern7zl4ahtlhd5t2",
  },
  terra1w7zgkcyt7y4zpct9dw8mw362ywvdlydnum2awa: {
    id: "mirrored-alibaba",
    symbol: "mbaba",
    name: "Mirrored Alibaba",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/BABA.png",
    decimals: 6,
    address: "terra1w7zgkcyt7y4zpct9dw8mw362ywvdlydnum2awa",
  },
  terra15hp9pr8y4qsvqvxf3m4xeptlk7l8h60634gqec: {
    id: "mirrored-ishares-gold-trust",
    symbol: "miau",
    name: "Mirrored iShares Gold Trust",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/IAU.png",
    decimals: 6,
    address: "terra15hp9pr8y4qsvqvxf3m4xeptlk7l8h60634gqec",
  },
  terra1kscs6uhrqwy6rx5kuw5lwpuqvm3t6j2d6uf2lp: {
    id: "mirrored-ishares-silver-trust",
    symbol: "mslv",
    name: "Mirrored iShares Silver Trust",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/SLV.png",
    decimals: 6,
    address: "terra1kscs6uhrqwy6rx5kuw5lwpuqvm3t6j2d6uf2lp",
  },
  terra1lvmx8fsagy70tv0fhmfzdw9h6s3sy4prz38ugf: {
    id: "mirrored-united-states-oil-fund",
    symbol: "muso",
    name: "Mirrored United States Oil Fund",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/USO.png",
    decimals: 6,
    address: "terra1lvmx8fsagy70tv0fhmfzdw9h6s3sy4prz38ugf",
  },
  terra1zp3a6q6q4953cz376906g5qfmxnlg77hx3te45: {
    id: "mirrored-proshares-vix",
    symbol: "mvixy",
    name: "Mirrored ProShares VIX",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/VIXY.png",
    decimals: 6,
    address: "terra1zp3a6q6q4953cz376906g5qfmxnlg77hx3te45",
  },
  terra1g4x2pzmkc9z3mseewxf758rllg08z3797xly0n: {
    id: "mirrored-airbnb",
    symbol: "mabnb",
    name: "Mirrored Airbnb",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/ABNB.png",
    decimals: 6,
    address: "terra1g4x2pzmkc9z3mseewxf758rllg08z3797xly0n",
  },
  terra1rhhvx8nzfrx5fufkuft06q5marfkucdqwq5sjw: {
    id: "mirrored-bitcoin",
    symbol: "mbtc",
    name: "Mirrored Bitcoin",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/icon/BTC.png",
    decimals: 6,
    address: "terra1rhhvx8nzfrx5fufkuft06q5marfkucdqwq5sjw",
  },
  terra1dk3g53js3034x4v5c3vavhj2738une880yu6kx: {
    id: "mirrored-ether",
    symbol: "meth",
    name: "Mirrored Ether",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/icon/ETH.png",
    decimals: 6,
    address: "terra1dk3g53js3034x4v5c3vavhj2738une880yu6kx",
  },
  terra1qelfthdanju7wavc5tq0k5r0rhsyzyyrsn09qy: {
    id: "mirrored-amc-entertainment",
    symbol: "mamc",
    name: "Mirrored AMC Entertainment",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/icon/AMC.png",
    decimals: 6,
    address: "terra1qelfthdanju7wavc5tq0k5r0rhsyzyyrsn09qy",
  },
  terra1m6j6j9gw728n82k78s0j9kq8l5p6ne0xcc820p: {
    id: "mirrored-gamestop",
    symbol: "mgme",
    name: "Mirrored GameStop",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/images/GME.png",
    decimals: 6,
    address: "terra1m6j6j9gw728n82k78s0j9kq8l5p6ne0xcc820p",
  },
  terra1mqsjugsugfprn3cvgxsrr8akkvdxv2pzc74us7: {
    id: "mirrored-facebook",
    symbol: "mfb",
    name: "Mirrored Facebook",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/icon/FB.png",
    decimals: 6,
    address: "terra1mqsjugsugfprn3cvgxsrr8akkvdxv2pzc74us7",
  },
  terra137drsu8gce5thf6jr5mxlfghw36rpljt3zj73v: {
    id: "mirrored-goldman-sachs",
    symbol: "mgs",
    name: "Mirrored Goldman Sachs",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/icon/GS.png",
    decimals: 6,
    address: "terra137drsu8gce5thf6jr5mxlfghw36rpljt3zj73v",
  },
  terra1aa00lpfexyycedfg5k2p60l9djcmw0ue5l8fhc: {
    id: "mirrored-spy",
    symbol: "mspy",
    name: "Mirrored S7P 500",
    platform: Platform.TERRA,
    logo: "https://whitelist.mirror.finance/icon/GS.png",
    decimals: 6,
    address: "terra1aa00lpfexyycedfg5k2p60l9djcmw0ue5l8fhc",
  },
  terra_ust: {
    id: "terrausd",
    symbol: "ust",
    name: "TerraUSD",
    platform: Platform.TERRA,
    logo: "https://assets.terra.money/icon/60/UST.png",
    decimals: 6,
    address: "terra_ust",
  },
  uusd: {
    id: "terrausd",
    symbol: "ust",
    name: "TerraUSD",
    platform: Platform.TERRA,
    logo: "https://assets.terra.money/icon/60/UST.png",
    decimals: 6,
    address: "uusd",
  },
  uluna: {
    id: "terra-luna",
    symbol: "luna",
    name: "LUNA",
    platform: Platform.TERRA,
    logo: "https://assets.terra.money/icon/60/Luna.png",
    decimals: 6,
    address: "uluna",
  },
  bluna: {
    id: "terra-luna",
    symbol: "bluna",
    name: "Bonded LUNA",
    platform: Platform.TERRA,
    logo: "https://app.anchorprotocol.com/static/media/bluna.0f5e5a4f.svg",
    decimals: 6,
    address: "uluna",
  },
  ukrw: {
    id: "terra-krw",
    symbol: "krt",
    name: "TerraKRT",
    platform: Platform.TERRA,
    logo: "https://assets.terra.money/icon/60/KRT.png",
    decimals: 6,
    address: "ukrw",
  },
  terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76: {
    id: "anchor-protocol",
    symbol: "anc",
    name: "Anchor Protocol",
    platform: Platform.TERRA,
    logo: "https://app.anchorprotocol.com/static/media/anc@160.d97267d8.gif",
    decimals: 6,
    address: "terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76",
  },
};
